
# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # npm (JavaScript/TypeScript)
  - package-ecosystem: "npm"
    directories: 
      - "**/*"  # Recursively looks for package.json in root and subdirectories
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "06:00"  # 6 AM UTC, equivalent to 8 AM UTC+2
      timezone: "Etc/UTC"
    groups:
      default:
        applies-to: version-updates
        patterns:
          - "*"       # A wildcard that matches all dependencies in the package

  # Python (pip)
  - package-ecosystem: "pip"
    directories: 
      - "**/*"   # Recursively looks for requirements.txt in root and subdirectories
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "06:00"  # 6 AM UTC, equivalent to 8 AM UTC+2
      timezone: "Etc/UTC"
    groups:
      default:
        applies-to: version-updates
        patterns:
          - "*"       # A wildcard that matches all dependencies in the package

  # Terraform
  - package-ecosystem: "terraform"
    directories: 
      - "**/*"   # Recursively looks for Terraform files in root and subdirectories
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "06:00"  # 6 AM UTC, equivalent to 8 AM UTC+2
      timezone: "Etc/UTC"
    groups:
      default:
        applies-to: version-updates
        patterns:
          - "*"       # A wildcard that matches all dependencies in the package

  # Gradle (Java/Kotlin)
  - package-ecosystem: "gradle"
    directories: 
      - "**/*"   # Recursively looks for build.gradle in root and subdirectories
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "06:00"  # 6 AM UTC, equivalent to 8 AM UTC+2
      timezone: "Etc/UTC"
    groups:
      default:
        applies-to: version-updates
        patterns:
          - "*"       # A wildcard that matches all dependencies in the package

  # Maven (Java)
  - package-ecosystem: "maven"
    directories: 
      - "**/*"   # Recursively looks for pom.xml in root and subdirectories
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "06:00"  # 6 AM UTC, equivalent to 8 AM UTC+2
      timezone: "Etc/UTC"
    groups:
      default:
        applies-to: version-updates
        patterns:
          - "*"       # A wildcard that matches all dependencies in the package

  # Jib (Java Containerization via GitHub Actions)
  - package-ecosystem: "github-actions"
    directories: 
      - "**/*"   # Recursively looks for GitHub Action workflows in root and subdirectories
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "06:00"  # 6 AM UTC, equivalent to 8 AM UTC+2
      timezone: "Etc/UTC"
    groups:
      default:
        applies-to: version-updates
        patterns:
          - "*"       # A wildcard that matches all dependencies in the package

  # Docker (Dockerfile)
  - package-ecosystem: "docker"
    directories: 
      - "**/*"   # Recursively looks for Dockerfiles in root and subdirectories
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "06:00"  # 6 AM UTC, equivalent to 8 AM UTC+2
      timezone: "Etc/UTC"
    groups:
      default:
        applies-to: version-updates
        patterns:
          - "*"       # A wildcard that matches all dependencies in the package
